# Generated by Django 5.1.3 on 2026-03-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('league', models.CharField(choices=[('Pro', 'AKPC Pro League'), ('Super', 'AKPC Super League'), ('Base', 'AKPC Base League'), ('Reserve', 'AKPC Reserve League'), ('Rookie', 'AKPC Rookie League')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.CharField(blank=True, help_text='e.g. 5⭐️', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('CF', 'Center Forwards'), ('SS', 'Second Strikers'), ('RW', 'Right Wingers'), ('LW', 'Left Wingers'), ('AMF', 'Attacking Midfielders'), ('LMF', 'Left Midfielders'), ('RMF', 'Right Midfielders'), ('CMF', 'Center Midfielders'), ('DMF', 'Defensive Midfielders'), ('LB', 'Left Backs'), ('RB', 'Right Backs'), ('CB', 'Center Backs'), ('GK', 'Goalkeepers')], max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
        ),
    ]
