# Generated by Django 5.2.4 on 2025-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
