# Generated by Django 5.2.4 on 2025-09-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_player_market_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
    ]
