# Generated by Django 5.1.3 on 2026-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('CF', 'Center Forwards'), ('SS', 'Second Strikers'), ('RWF', 'Right Wingers'), ('LWF', 'Left Wingers'), ('AMF', 'Attacking Midfielders'), ('LMF', 'Left Midfielders'), ('RMF', 'Right Midfielders'), ('CMF', 'Center Midfielders'), ('DMF', 'Defensive Midfielders'), ('LB', 'Left Backs'), ('RB', 'Right Backs'), ('CB', 'Center Backs'), ('GK', 'Goalkeepers')], max_length=3),
        ),
    ]
